### ISSUE TITLE
Migrate to CMake

### ISSUE THREAD

**Issue by day-garwood** [samtupy/nvgt#135]
Hi there,
I'm wondering about the possibilities of migrating over to CMake for the build system.
I'm relatively new to build systems, but have been meaning to learn CMake for a while, and was thinking I could try and learn it through this.
Wanted to check first though, because there's no point me doing it if there's no interest in switching.
From a personal point of view, it would make it easier for me to contribute, because CMake is something I already have, and it doesn't mean potentially breaking Python installations with Pip and third party libraries and so on (yes, by some weird fluke I did somehow manage to break Python and Pip in the past!).
I guess another approach would be to have a CMake script as an alternative method of building for those who prefer that, similar to how AngelScript has multiple build projects, though not sure how much that would conflict with SCons.
Interested to hear thoughts on this.
Cheers.

**Comment by ethindp** [comment]
How exactly would you be unnecessarily polluting a Python install when the most you'll need to build NVGT itself is SCons? I'm pretty sure the general rule of thumb is that other build systems will be okay as long as you are willing to maintain them. The problem is that the SCons build system does some things that CMake does not actually normally allow you to do without some weird hackery (and the language itself is terrible) -- Meson would be a much better target. But again, you would need to maintain these alternative build systems yourself. We've talked about migrating to Meson but actually doing so is not a simple task.

**Comment by day-garwood** [comment]
To be fair, from what I've learned so far, I must say I don't much like the CMake language myself. All I know is, A, it's well known and well supported, B, it's not half as crinkled and baggy-eyed as make, and C, I only need to install one extra thing and not three.
Never heard of Meson. That makes me think it's not as popular, which could potentially make integrating other dependencies slightly more complicated. I'll have to have a look at that.
As for polluting Python installations... I dunno. All I know is I broke it once when I decided to give it a go and it's made me a little cautious of trying it again in a hurry. I guess the saving grace here is it doesn't enforce specific versions, which I think could well have been part of the issue last time - I really don't remember.

**Comment by ethindp** [comment]
Nah, Meson isn't "unpopular," it's just that CMake is used by so many people that it's difficult for any other build system to get in, even if Meson has CMake support to a degree. Ultimately though, I'm pretty sure (and Sam can confirm or deny of course) that if you do want to do this, it'll be something you'll have to maintain yourself, and it'll need to be alongside SCons.

**Comment by samtupy** [comment]
Hi,

Indeed if a pull request is opened with CMake support, I will not reject it. However, in practice, there are some things to consider, plugins being the biggest example. Right now, it's possible for anyone to make nvgt plugins in c++, then to slot them into the build system with small SConscript files. Though I have a bit of work yet to do here on Android, this system should work for all 5 platforms we intend to support meaning that NVGT plugin authors don't need to learn CMake or even much about SCons to implement a static build of their plugin into the system. Could CMake offer similar configuration?

Another thing to consider is that this likely won't satisfy all, either. Some people want a visual studio solution, some want a CMake project, some want meson and for me SCons works just fine. So indeed my policy here has ended up being that if people want to contribute unofficial build systems, I won't reject them, they might make things convenient for that subset of users that wish to use a given build system. However not from lack of caring but instead from lack of extra room in my brain to shove all this build system knowledge, I don't think I could actively maintain more than one build system myself. I don't know CMake and I don't know meson, and already I find myself flirting with scons sometimes when trying to just work on NVGT in general. If the task of changing anything in NVGT's ccodebase beyond the contents of existing files starts to involve making sure 3 build systems work on 5 platforms, I could see myself potentially burning out super fast. Thus while I won't reject any alternate build scripts, I can't commit to maintaining them right now myself.

As for scons messing with your python packages, perhaps a virtual environment could be used? I admit to needing to learn these myself and when I do I could update the build scripts to use one as well as nvgt's readme.md, but that would probably  solve any potential issues with your python system packages. Indeed we've run into it before probably due to the lack of a virtual environment and it is only a matter of time before we fix that at least in our scripts.

A potential workaround though I have not actually tried to use this myself is to use the [scons local bundle](http://prdownloads.sourceforge.net/scons/scons-local-4.8.1.zip) which you could just dump into the nvgt repository as opposed to installing scons.

**Comment by day-garwood** [comment]
I have discounted Meson because that also requires Python. To be honest I have actually given up on CMake now, as the language is far too weird to get my head around, despite reading two tutorials and one 42 chapter book. It's nice to build with but horrible to script with. You do make a good point about Android though - I know CMake can work with Apple packages and frameworks but I don't remember reading anything about Android (though I could be wrong there). It can generate lots of other build systems though such as regular makefiles, Visual Studio projects, Ninja and so on.
I'm currently looking into Premake which is just a single executable with Lua scripting. It can also build regular makefiles or VS projects, not sure it can build much else right now, but it is open source (written in C and Lua) and easily extendable, so I'm sure it could be extended to support Android or Apple for those who know those platforms well (unfortunately I don't so chances of me being able to do that are close to nil).
I don't know much about virtual environments. I know my server runs on a virtual machine but beyond that I don't know much at all. Always open to learning though. SCons does look relatively simple if I can get over this fear of Python. As I say I'd love to be able to contribute.
I'll close this particular issue though as, when all is said and done, it sounds to me like you probably have got the best system for the job.
