### ISSUE TITLE
a modification to compiling script

### ISSUE THREAD

**Issue by peter1384** [samtupy/nvgt#19]
in bgt, when we had a script and we compiled it, it would only compile if it didn't have compilation error. But, in nvgt,  Everything is being compiled to .exe, even if it has compilation errors, then when we press enter on the compiled .exe file, we would get compilation error
But bgt was acting correctly about this, because any building system, python, c++, etc, wouldn't give you .exe file if it had compilation error.
would this get fix? or it is done for a reason? Thanks.

**Comment by samtupy** [comment]
Hi,
So there should only be one case of this, and bgt actually suffers the same issue. If you compile a script specifically without an entry point (void main or int main), the app will compile as there are no actual syntax errors in your code, but then the engine errors out because it can't call a specific function in the compiled code.
It does seem like it would be better user interface indeed however to do a check for the main function as part of the compilation process as well, so we can certainly do that in the future.
If there is another case you know about that can generate this behavior, can you please post an example script?
Thanks.

**Comment by peter1384** [comment]
it can be anything, for example, follow the steps below.
in nvgt
1: press application on music.nvgt, which is inside the inclood folder, and compile it as releace for example
2: you will see that it showes a dialog box saying the script has been compiled and saved in blaablaablaa, and then we have a music.exe file added in there
3: press enter on music.exe, you'll see compilation error dialog appearing
in bgt
1: try to compile logger.bgt or form.bgt or whatever file inside the inclood folder as releace or debug doesn't matter, and you'll see that it gives compilation error and doesn't compile, and doesn't give you the exe file from that script all.
in steps above, bgt does the correct job and nvgt should become like bgt in this case. Hopefully I was clear and specific enough
Thanks
