### ISSUE TITLE
Problem including bgt_compat

### ISSUE THREAD

**Issue by Reyes2005** [samtupy/nvgt#3]
Hello, first of all congratulations on this great project, I sincerely hope that it continues like this to have an even more complete engine if possible.
I come to report an error when including the bgt_compat.nvgt file, because doing so shows an error related to internet_request not being an available data type. Below I paste the full error for more details:
file: C:/nvgt/include/bgt_compat.nvgt
line: 355 (1)
INFO: Compiling string url_get(const string&in)

file: C:/nvgt/include/bgt_compat.nvgt
line: 356 (2)
ERROR: Identifier 'internet_request' is not a data type

file: C:/nvgt/include/bgt_compat.nvgt
line: 360 (1)
INFO: Compiling string url_post(const string&in, const string&in)

file: C:/nvgt/include/bgt_compat.nvgt
line: 361 (2)
ERROR: Identifier 'internet_request' is not a data type

I don't remember exactly if this had already been explained, but I'm reporting it here anyway so it can be reviewed.

**Comment by samtupy** [comment]
Hi, you can temporarily get around this error by including the line
`#pragma plugin nvgt_curl`
at the top of your script.
The error is happening because we are in the middle of transitioning to a new http library which will cause the url_get and url_post functions to be built into the engine instead of being a part of bgt_compat.
It should be solved properly in the next day or 2.
Thank you!

**Comment by samtupy** [comment]
This was fixed in commit 89475abbeab9d310e22a1509288fba004008db61, thank you and sorry for the trouble!
